import 'package:flutter/material.dart';
import '../widgets/app_footer.dart';
import '../widgets/market_price_card.dart';

class MarketPricesPage extends StatelessWidget {
  final String searchQuery;
  const MarketPricesPage({super.key, required this.searchQuery});

  @override
  Widget build(BuildContext context) {
    final List<Map<String, String>> data = [
      {"crop": "Wheat ", "price": "₹31.82/kg"},
      {"crop": "Rice ", "price": "₹43.22"},
      {"crop": "Tur/Arhar Dal", "price": "₹116.05/kg"},
      {"crop": "Sugar", "price": "₹46.39/kg"},
      {"crop": "Potato", "price": "₹24.07/kg"},
      {"crop": "Onion", "price": "₹32/kg"},
      {"crop": "Tomato", "price": "₹57.55/kg"},
      {"crop": "Brinjal", "price": "₹42.41/kg"},
      {"crop": "Lady Finger(Okra)", "price": "₹30-40/kg"},
      {"crop": "CauliFlower", "price": "₹40-60/kg"},
      {"crop": "Banana", "price": "₹47.02/kg"},
      {"crop": "Papaya", "price": "₹35/kg"},
      {"crop": "Pomegranate", "price": "₹130/kg"},
      {"crop": "Apple", "price": "₹140-170/kg"},
      {"crop": "Cardamom", "price": "₹2500/kg"},
      {"crop": "Cucumber", "price": "₹40/kg"},
      {"crop": "Green Pea", "price": "₹35/kg"},
      {"crop": "Garlic", "price": "₹125/kg"},
      {"crop": "Turmeric", "price": "₹150/kg"},
      {"crop": "Green Chilli", "price": "₹53-58/kg"},
      {"crop": "Beetroot", "price": "₹45/kg"},
      {"crop": "Raw Banana", "price": "₹17/kg"},
      {"crop": "Amaranth Leaves", "price": "₹14/kg"},
      {"crop": "Amla", "price": "₹65/kg"},
      {"crop": "Baby Corn", "price": "₹54/kg"},
      {"crop": "Banana Flower", "price": "₹15/kg"},
      {"crop": "Capsicum", "price": "₹50/kg"},
      {"crop": "Bitter Gourd", "price": "₹39/kg"},
      {"crop": "Bottle Gourd", "price": "₹30/kg"},
      {"crop": "Butter Beans", "price": "₹46/kg"},
      {"crop": "Cabbage", "price": "₹27/kg"},
      {"crop": "Carrot", "price": "₹43/kg"},
      {"crop": "Coconut", "price": "₹66/kg"},
      {"crop": "Corn", "price": "32/kg"},
      {"crop": "Pomegranate", "price": "₹70/Piece"},
      {"crop": "RamPhal Fruit", "price": "₹350/kg"},
      {"crop": "Smart Papaya", "price": "₹40/kg"},
      {"crop": "Cucumber", "price": "₹30/kg"},
      {"crop": "Ginger", "price": "₹77/kg"},
      {"crop": "Mushroom", "price": "₹99/kg"},
      {"crop": "Jamun", "price": "₹140-170/kg"},
      {"crop": "Mustard Leaves ", "price": "₹15/kg"},
      {"crop": "Radish", "price": "₹34/kg"},
      {"crop": "Spinach", "price": "₹13/kg"},
      {"crop": "Sweet Potato", "price": "₹58/kg"},
      {"crop": "Lemon", "price": "₹56/kg"},
      {"crop": "Garlic", "price": "₹98/kg"},
      {"crop": "Ginger", "price": "₹77/kg"},
      {"crop": "Rose (Local)", "price": "₹150/kg"},
      {"crop": "Marigold (Yellow)", "price": "₹60/kg"},
      {"crop": "Marigold (Orange)", "price": "₹70/kg"},
      {"crop": "Jasmine (Mogra)", "price": "₹450/kg"},
      {"crop": "Chrysanthemum", "price": "₹120/kg"},
      {"crop": "Tuberose (Rajnigandha)", "price": "₹250/kg"},
      {"crop": "Lotus", "price": "₹25/piece"},
      {"crop": "Gerbera", "price": "₹15/piece"},
      {"crop": "Orchid", "price": "₹60/stick"},
      {"crop": "Carnation", "price": "₹20/piece"},
      {"crop": "Bajra (Pearl Millet)", "price": "₹28/kg"},
      {"crop": "Jowar (Sorghum)", "price": "₹42/kg"},
      {"crop": "Ragi (Finger Millet)", "price": "₹48/kg"},
      {"crop": "Barley (Jau)", "price": "₹32/kg"},
      {"crop": "Maize (Corn Grain)", "price": "₹25/kg"},
      {"crop": "Black Gram (Urad Whole)", "price": "₹115/kg"},
      {"crop": "Green Gram (Moong Whole)", "price": "₹105/kg"},
      {"crop": "Lentil (Masoor Dal)", "price": "₹92/kg"},
      {"crop": "Chickpeas (Kabuli Chana)", "price": "₹135/kg"},
      {"crop": "Soybean", "price": "₹52/kg"},
      {"crop": "Mustard Seeds (Rai)", "price": "₹75/kg"},
      {"crop": "Cumin (Jeera)", "price": "₹285/kg"},
      {"crop": "Fennel Seeds (Saunf)", "price": "₹180/kg"},
      {"crop": "Black Pepper", "price": "₹650/kg"},
      {"crop": "Cloves", "price": "₹950/kg"},
      {"crop": "Cinnamon", "price": "₹450/kg"},
      {"crop": "Fenugreek Seeds", "price": "₹85/kg"},
      {"crop": "Dry Red Chilli", "price": "₹220/kg"},
      {"crop": "Coriander Seeds", "price": "₹145/kg"},
      {"crop": "Sesame Seeds (Til)", "price": "₹190/kg"},
      {"crop": "Guava (Allahabadi)", "price": "₹55/kg"},
      {"crop": "Grapes (Black)", "price": "₹125/kg"},
      {"crop": "Grapes (Green Seedless)", "price": "₹95/kg"},
      {"crop": "Sapota (Chiku)", "price": "₹45/kg"},
      {"crop": "Custard Apple (Sitaphal)", "price": "₹85/kg"},
      {"crop": "Kiwi", "price": "₹35/piece"},
      {"crop": "Dragon Fruit", "price": "₹80/piece"},
      {"crop": "Musk Melon", "price": "₹50/kg"},
      {"crop": "Water Melon", "price": "₹30/kg"},
      {"crop": "Orange (Nagpur)", "price": "₹65/kg"},
      {"crop": "Kinnow", "price": "₹45/kg"},
      {"crop": "Pineapple (Rani)", "price": "₹75/piece"},
      {"crop": "Pear (Nashpati)", "price": "₹90/kg"},
      {"crop": "Plum", "price": "₹160/kg"},
      {"crop": "Strawberry", "price": "₹60/packet"},
      {"crop": "Blueberry", "price": "₹250/packet"},
      {"crop": "Avocado", "price": "₹150/piece"},
      {"crop": "Sweet Lime (Mosambi)", "price": "₹55/kg"},
      {"crop": "Wood Apple (Bel)", "price": "₹30/piece"},
      {"crop": "Jackfruit", "price": "₹45/kg"},
      {"crop": "Ber (Jujube)", "price": "₹40/kg"},
      {"crop": "Dates (Dry)", "price": "₹280/kg"},
      {"crop": "Figs (Fresh)", "price": "₹180/kg"},
      {"crop": "Star Fruit", "price": "₹40/kg"},
      {"crop": "Mulberry", "price": "₹120/kg"},
      {"crop": "Passion Fruit", "price": "₹220/kg"},
      {"crop": "Peach", "price": "₹140/kg"},
      {"crop": "Apricot", "price": "₹250/kg"},
      {"crop": "Litchi", "price": "₹200/kg"},
      {"crop": "Coconut (Dry/Gola)", "price": "₹160/kg"},
      {"crop": "French Beans", "price": "₹45/kg"},
      {"crop": "Ash Gourd", "price": "₹28/kg"},
      {"crop": "Snake Gourd", "price": "₹42/kg"},
      {"crop": "Cluster Beans", "price": "₹35/kg"},
      {"crop": "Drumstick", "price": "₹185/kg"},
      {"crop": "Colocasia (Arbi)", "price": "₹40/kg"},
      {"crop": "Elephant Foot Yam", "price": "₹38/kg"},
      {"crop": "Tinda (Apple Gourd)", "price": "₹28/kg"},
      {"crop": "Pointed Gourd (Parwal)", "price": "₹55/kg"},
      {"crop": "Ridge Gourd", "price": "₹40/kg"},
      {"crop": "Sponge Gourd", "price": "₹35/kg"},
      {"crop": "Ivy Gourd (Kundru)", "price": "₹32/kg"},
      {"crop": "Spring Onion", "price": "₹25/bundle"},
      {"crop": "Broccoli", "price": "₹90/kg"},
      {"crop": "Red Cabbage", "price": "₹45/kg"},
      {"crop": "Sweet Corn", "price": "₹35/kg"},
      {"crop": "Green Peas (Premium)", "price": "₹42/kg"},
      {"crop": "Raw Papaya", "price": "₹28/kg"},
      {"crop": "Yam (Ratalu)", "price": "₹45/kg"},
      {"crop": "Methi (Fenugreek Leaves)", "price": "₹15/bundle"},
      {"crop": "Coriander Leaves", "price": "₹22/kg"},
      {"crop": "Mint Leaves", "price": "₹25/bundle"},
      {"crop": "Curry Leaves", "price": "₹10/bundle"},
      {"crop": "Turnip (Shalgam)", "price": "₹30/kg"},
      {"crop": "Zucchini (Green)", "price": "₹75/kg"},
      {"crop": "Zucchini (Yellow)", "price": "₹85/kg"},
      {"crop": "Lettuce", "price": "₹60/kg"},
      {"crop": "Celery", "price": "₹45/bundle"},
      {"crop": "Leeks", "price": "₹50/kg"},
      {"crop": "Cherry Tomato", "price": "₹120/kg"},
      {"crop": "Bok Choy", "price": "₹80/kg"},
      {"crop": "Asparagus", "price": "₹450/kg"},
      {"crop": "Brussel Sprouts", "price": "₹180/kg"},
      {"crop": "Baby Potatoes", "price": "₹28/kg"},
      {"crop": "Chinese Cabbage", "price": "₹40/kg"},
      {"crop": "Snow Peas", "price": "₹250/kg"},
      {"crop": "Water Chestnut (Singhara)", "price": "₹65/kg"},
      {"crop": "Lotus Stem (Kamal Kakdi)", "price": "₹55/kg"},
      {"crop": "Kohlrabi (Ganth Gobi)", "price": "₹35/kg"},
      {"crop": "Green Garlic", "price": "₹40/bundle"}
    ];

    final filteredList = data.where((item) {
      return item['crop']!.toLowerCase().contains(searchQuery);
    }).toList();

    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      physics: BouncingScrollPhysics(),
      child: Column(
        children: [
          const SizedBox(height: 10),
          // Using ListView.shrinkWrap to allow it to sit above the footer
          ListView.builder(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: filteredList.length,
            itemBuilder: (context, index) => MarketPriceCard(
              crop: filteredList[index]['crop']!,
              price: filteredList[index]['price']!,
            ),
          ),
          const SizedBox(height: 40),
          const AppFooter(), // Footer added here
        ],
      ),
    );
  }
}